### PR TITLE
Add Now to build docs page

### PR DESCRIPTION
**Pull request by dacsang97**

### CODE REVIEW

**Comment by flozero** [comment]
Did you see my plugin and the deploy sh ? It can help. It let you auto deplo on a branch gh-branch and with this it automatically create github page host

**Comment by dacsang97** [comment]
Oh I miss it, but I think we should use Now because with alias we have prettier URL than the gh-page URL

**Comment by flozero** [comment]
Ok i see. What is the url so with the alias ?

**Review by flozero — APPROVED** [review]
Ok for me

**Pull request merged**
