### PR TITLE
Feature/vue doc gen api upgrade

### PR DESCRIPTION
**Pull request by flozero**
Changed the template from src/template/component.ts

comment the props replace string. Need some answear on it

look's like 

capture d ecran 2019-01-14 a 00 16 42

I let you watch the code and tell me

### CODE REVIEW

**Comment by flozero** [comment]
I do not yet take all informations from vue-doc gen api but for me the most important. Easy to add features on it like authors deprecated etc. (Most of them are tags)

I didn't take care of mixins and slots maybes it should be added here (vue-styleguidist use them)

**Review by dacsang97 — APPROVED** [review]
Good job. Thank for your supporting.

**Comment by flozero** [comment]
> Good job. Thank for your supporting.

nice ! 👍

feel free to add me as contributor :) I will help you to maintain it and add unit test etc :)

I can suggest you to github page the repo

https://github.com/f3ltron/vuepress-plugin-prismjs as i did here :)

see my deploy.sh

**Comment by dacsang97** [comment]
Nice work 🍡

**Review by dacsang97 — APPROVED** [review]

**Pull request merged**
